# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: epoch-processor
#   annotations:
#     autoscaling.keda.sh/paused: "true"
# spec:
#   pollingInterval: 15
#   idleReplicaCount: 0
#   minReplicaCount: 1
#   maxReplicaCount: 30
#   fallback:
#     failureThreshold: 3
#     replicas: {{ .Values.ingest.replicaCount }}
#   scaleTargetRef:
#     name: epoch-processor
#     kind: StatefulSet
#     apiVersion: apps/v1
#   triggers:
#   - type: redis
#     metadata:
#       host: car-processing-redis-headless.{{ .Release.Namespace }}.svc.cluster.local
#       port: "6379"
#       listName: {{ .Values.ingest.redis.list }}
#     authenticationRef:
#       name: keda-redis-stream-triggerauth