
apiVersion: v1
kind: Secret
metadata:
  name: storage-config
type: Opaque
stringData:
  AWS_ENDPOINT: {{ .Values.aws.endpoint | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}

