apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: epoch-processor
spec:
  serviceName: epoch-processor
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: epoch-processor
  template:
    metadata:
      labels:
        app: epoch-processor
    spec:
      containers:
      - name: epoch-processor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: car-processing-redis
              key: redis-password
        - name: CONSUMER
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: storage-config
        - configMapRef:
            name: car-processing-config
        volumeMounts:
        - name: epoch-processor-storage
          mountPath: /data
        resources:
          requests:
            memory: "10Gi"
            cpu: "1"
          limits:
            memory: "20Gi"
            cpu: "2"
      imagePullSecrets:
      - name: docker-registry-secret
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: epoch-processor-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ssd-large"
      resources:
        requests:
          storage: 1000Gi